[platformio]
name = Kortlinje
description = RP2350 mod for IKEA Kortlinje alarm clock
core_dir = .platformio
include_dir = firmware/include
src_dir = firmware/src

[env]
platform = https://api.github.com/repos/maxgerhardt/platform-raspberrypi/tarball/5d4561a05e3b212660ac6fdd3fbfb328d1988aa1
framework = arduino
monitor_speed = 115200
monitor_filters =
	log2file
	time
build_flags =
	-std=gnu++23
	-Wl,-u,_printf_float
build_unflags = -std=gnu++17
board_build.filesystem_size = 2m
;upload_protocol = espota
;upload_port = kortlinje.local

[env:rpipico2w]
board = rpipico2w
