name: Context

on:
  workflow_call:
    outputs:
      pio-environments:
        description: "PlatformIO environments"
        value: ${{ jobs.environments.outputs.pio }}

  workflow_dispatch:

permissions:
  contents: read

jobs:
  cache:
    name: PlatformIO cache
    runs-on: ubuntu-latest
    concurrency:
      group: pio-cache
      queue: max

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Cache for PlatformIO
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache
        with:
          key: platformio-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('platformio.ini') }}
          path: .platformio/.cache/downloads
          lookup-only: true

      - name: Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          python-version: 3.11
          version: latest-known

      - name: PlatformIO package install
        if: steps.cache.outputs.cache-hit != 'true'
        run: uv run pio pkg install

  environments:
    name: PlatformIO environments
    runs-on: ubuntu-latest
    outputs:
      pio: ${{ steps.platformio.outputs.environments }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: 3.11
          version: latest-known

      - name: PlatformIO environments
        id: platformio
        run: echo "environments=$(uv run pio project config --json-output | jq -c '[.[] | .[0] | select(startswith("env:")) | sub("^env:"; "")]')" >> "$GITHUB_OUTPUT"
