name: Dependabot Updates PlatformIO

on:
  schedule:
    - cron: 9 5 * * 1-5

  workflow_dispatch:

permissions:
  contents: read

jobs:
  platformio:
    name: Update PlatformIO dependencies
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: PlatformIO Dependency Updater
        uses: VIPnytt/platformio-dependency-updater@668392cba27a595fa823de4f68ab42ec0dad5d42 # v1.0.3
